<?php

/**
 * @file
 * Contains glico_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;

define('SHORTEN_LINK_SERVICE', 'bit.ly');
define('ROLE_ADMIN', 'administrator');
define('ROLE_MOD', 'moderator');

/**
 * Implements hook_help().
 */
function glico_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the glico_custom module.
    case 'help.page.glico_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Glico Custom Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function glico_custom_theme() {
  return [
    'glico_custom' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_create
 */
function glico_custom_node_create(NodeInterface $node) {
  if ($node->getType() == 'submission') {
    $node->title = 'Video dự thi';
  }
}

function glico_custom_node_insert(NodeInterface $node) {
  if ($node->getType() == 'submission') {
    $nid = $node->id();
    $node_url = Url::fromRoute('entity.node.canonical', ['node' => $nid], ['absolute' => TRUE])->toString();
    $node_url = str_replace('node', 'video', $node_url);
    $node->field_shorten_link = shorten_url($node_url, SHORTEN_LINK_SERVICE);
    $node->save();
  }
}